[[Atomsk]]
arch = "aarch64"
git-tree-sha1 = "fe9cd0aa40ddad8578342b736e126c80fb9e08d9"
libgfortran_version = "5.0.0"
os = "macos"

    [[Atomsk.download]]
    sha256 = "06e732cdb2698c77bfa6f569c421411f704b8bc2120e31771e839fad6b81b1ba"
    url = "https://github.com/JuliaBinaryWrappers/Atomsk_jll.jl/releases/download/Atomsk-v0.12.0+0/Atomsk.v0.12.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Atomsk]]
arch = "aarch64"
git-tree-sha1 = "826e7fed01bdb9ff4b21937befab13d92cfd8430"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Atomsk.download]]
    sha256 = "a53068d85026d23d1fc72081315879f7b838cc56ffe0f5613d1724ff258dde99"
    url = "https://github.com/JuliaBinaryWrappers/Atomsk_jll.jl/releases/download/Atomsk-v0.12.0+0/Atomsk.v0.12.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Atomsk]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a44ce0f1cf0bad382638d837a2527257539313a8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Atomsk.download]]
    sha256 = "cae66d444f74f7cc2e44ef07d9b1bc74006621625d74207a5a90f30e8db1ad04"
    url = "https://github.com/JuliaBinaryWrappers/Atomsk_jll.jl/releases/download/Atomsk-v0.12.0+0/Atomsk.v0.12.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Atomsk]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6fab33a610e6a6306cfb3cfc84c84afea4cba62e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Atomsk.download]]
    sha256 = "f980d1a26a25a98f13d320918b17549c39829d80ddab503fb1a5ce65ea16867c"
    url = "https://github.com/JuliaBinaryWrappers/Atomsk_jll.jl/releases/download/Atomsk-v0.12.0+0/Atomsk.v0.12.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Atomsk]]
arch = "i686"
git-tree-sha1 = "f0974a8851e523854df3784e5f39399741f11a5b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Atomsk.download]]
    sha256 = "7bcc50664aa827728b32194bc3e1344ecbd6d8be9b144d3c0c10276da43b8d6c"
    url = "https://github.com/JuliaBinaryWrappers/Atomsk_jll.jl/releases/download/Atomsk-v0.12.0+0/Atomsk.v0.12.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Atomsk]]
arch = "i686"
git-tree-sha1 = "aa35e2f100fa380d7698a20cf977374243b6ee3b"
libgfortran_version = "5.0.0"
os = "windows"

    [[Atomsk.download]]
    sha256 = "464a67e046177f41c1d5662985b712af3a1864f95fad091d11c8813448daf627"
    url = "https://github.com/JuliaBinaryWrappers/Atomsk_jll.jl/releases/download/Atomsk-v0.12.0+0/Atomsk.v0.12.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Atomsk]]
arch = "powerpc64le"
git-tree-sha1 = "79544acba013550411c49e9e1a826e8c1c090671"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Atomsk.download]]
    sha256 = "bb9c330fe8005a1460dd21e278a37de3135f3a69801ce8df7fe8c70f0f8c307b"
    url = "https://github.com/JuliaBinaryWrappers/Atomsk_jll.jl/releases/download/Atomsk-v0.12.0+0/Atomsk.v0.12.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Atomsk]]
arch = "x86_64"
git-tree-sha1 = "9d0a11311c0dc48d6133eec7e1ce6d53be599667"
libgfortran_version = "5.0.0"
os = "macos"

    [[Atomsk.download]]
    sha256 = "9447bc2cf4f3b257e52ed70e7249cbe92ab95d0eeb05954eb31453e7fd8cc607"
    url = "https://github.com/JuliaBinaryWrappers/Atomsk_jll.jl/releases/download/Atomsk-v0.12.0+0/Atomsk.v0.12.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Atomsk]]
arch = "x86_64"
git-tree-sha1 = "160326d44004b4b356275f9085337fac1d63b89e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Atomsk.download]]
    sha256 = "14a74969a86e295e8f6608b13010397c1b8b1c54ec65b96abf92894ff01365cd"
    url = "https://github.com/JuliaBinaryWrappers/Atomsk_jll.jl/releases/download/Atomsk-v0.12.0+0/Atomsk.v0.12.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Atomsk]]
arch = "x86_64"
git-tree-sha1 = "ba382469e2aef76ca1b7a7f8ee7335a49b3af5f1"
libgfortran_version = "5.0.0"
os = "windows"

    [[Atomsk.download]]
    sha256 = "8a6328d07adabeed1101b40581f27e876b59ced87f8b46425aba48a660768ec1"
    url = "https://github.com/JuliaBinaryWrappers/Atomsk_jll.jl/releases/download/Atomsk-v0.12.0+0/Atomsk.v0.12.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
